data_loader:
  file_path: "data/updated_pollution_dataset.csv"
  file_type: "csv"

transformation:
  normalize: false
  scaling_method: "minmax"

model:
  type: "decisiontree" # Options: "logistic" or "decisiontree"
  params : {}

splitting:
  test_size: 0.2

mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "air_pollution_experiments"

